sftp:
  HOST: localhost
  PORT: "11122"
  USER: naru
  PASSWORD: naru0914
#  PRIVATE_KEY: c:\lab\ssis\secret\id_rsa
#  PRIVATE_KEY_PASSPHRASE:
  REMOTE_DIR: /home/naru/storage

app:
  default-log-directory: /Users/kiwi/lab/project/log-trans/sample-log
  hash-algorithm: SHA-256
  etc:
    LOG_PATH: /Users/kiwi/lab/project/log-trans/logs
